locale = "zh-cn" # zh-tw, en, jp, kr ...

# 枚举表
enumFile = "xlsx/enum.xlsx"

# 多语言表
localeFile = "xlsx/多语言表.xlsx"

# 数据表头几行忽略(表头)
ignoreLine = 4

[tables]
  [tables.global]
  workbook = "xlsx/全局配置表.xlsx"
  horizontal = true

  [tables.npc]
  workbook = "xlsx/npc表.xlsx"
  horizontal = false
  enums = [
      {field = "task_id", table = "task"},
  ]

  [tables.task]
  workbook = "xlsx/任务表.xlsx"
  horizontal = false
  enums = [
      {field = "need_id", table = "item"},
      {field = "award_id", table = "item"},
  ]

  [tables.location]
  workbook = "xlsx/位置表.xlsx"
  horizontal = false
  enums = [
      {field = "shop_list", table = "shop"},
      {field = "npc_id", table = "npc"},
      {field = "star", table = "enum", sheet = "星级"},
  ]

  [tables.shop]
  workbook = "xlsx/市场表.xlsx"
  horizontal = false
  enums = [
      {field = "sell_id", table = "fabao"},
      {field = "buy_id", table = "fabao"},
  ]

  [tables.fabao]
  workbook = "xlsx/法宝表.xlsx"
  horizontal = false
  enums = [
      {field = "star", table = "enum", sheet = "星级"},
      {field = "attr", table = "enum", sheet = "属性"},
  ]

  [tables.spell]
    workbook = "xlsx/法术表.xlsx"
    horizontal = false
    enums = [
        {field = "star", table = "enum", sheet = "星级"},
        {field = "attr", table = "enum", sheet = "属性"},
        {field = "cast_type", table = "enum", sheet = "出手类型"},
        {field = "cast_attr", table = "enum", sheet = "属性"},
    ]

  [tables.item]
  workbook = "xlsx/物品表.xlsx"
  horizontal = false
  enums = [
      {field = "award_id", table = "item,spell"},
  ]

