locale = "zh-cn" # zh-tw, en, jp, kr ...

# 枚举表
enumFile = "xlsx/enum.xlsx"

# 多语言表
localeFile = "xlsx/多语言表.xlsx"

# 数据表头几行忽略(表头)
ignoreLine = 4

[tables]
  [tables.global]
  workbook = "xlsx/全局配置表.xlsx"
  horizontal = true

#  [tables.fabao]
#  workbook = "xlsx/法宝表.xlsx"
#  autoId = true
#  horizontal = false
#  enums = [
#    {field = "class_1", table = "物品大类"},
#    {field = "class_2", table = "物品小类"},
#    {field = "size", table = "尺寸"},
#  ]

#  [tables.location]
#  workbook = "xlsx/位置表.xlsx"
#  horizontal = false
#  enums = [
#      {field = "shop_list", table = "市场表"},
#      {field = "npc_id", table = "npc表"},
#      {field = "star", table = "enum", sheet = "星级"},
#  ]

  [tables.shop]
  workbook = "xlsx/市场表.xlsx"
  horizontal = false
  enums = [
      {field = "sell_id", table = "fabao"},
      {field = "buy_id", table = "fabao"},
  ]

  [tables.fabao]
  workbook = "xlsx/法宝表.xlsx"
  horizontal = false
  enums = [
      {field = "star", table = "enum", sheet = "星级"},
      {field = "attr", table = "enum", sheet = "力量属性"},
  ]

