locale = "zh-cn" # zh-tw, en, jp, kr ...

# 枚举表
enumFile = "xlsx/enum.xlsx"

# 多语言表
localeFile = "xlsx/多语言表.xlsx"

# 数据表头几行忽略(表头)
ignoreLine = 4

[tables]
  [tables.equip]
  #sheet = "装备"
  workbook = "xlsx/装备表.xlsx"
  autoId = true
  horizontal = false
  enums = [
    {field = "class_1", table = "物品大类"},
    {field = "class_2", table = "物品小类"},
    {field = "size", table = "尺寸"},
  ]

  [tables.location]
    #sheet = "装备"
    workbook = "xlsx/位置表.xlsx"
    autoId = true
    horizontal = false

  #locates = [
  #  {field = "name", table = "描述"}
  #]
